sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: edIQHaRk9OajY9YGU6bcO/pkInxJrT5MltcsxZNmk1A3PyKjJdLV/2DeHWyn0GvW4TU939nk4dEpLrp11Qo7nwRMuEMZ9KXvxP/UgrrwlzhYjirgbXT58s24Ka60d2oD/6oSEpdSx6aNmghHm0eK82AmmGPeCRVMF7xZxjjcEiFFgSJ+n5PDu606PudZSyUPXySQWCi/XaORdemd8nD/macpr0vNIDvg74kEJSyBV5YUElQjVKG1cWYtJncR6P9y7rYdO2FqCx45TvuTzbRPcbQ/NL+EuLHsR2VkLifphHjNCECMH4KbIcWJroJTwSaPjTxNoQ3F1ozKEPxF3rD56Okodny4wqaAdtHHOUxNLmjmKu4BVBqoaLLJTqE2rxRkKZYAC+1P1EZ/+kJGmcfEVAlvz/Nbh/qlKTKunm5h5sBZAwS7XaeDlm1NcSBJ/qlT7E6lcp46xu63ly+3zP7Okj7paU9DTZg02GGYbF3nkAOJ4/WJv9cXXpFgDp31EL/V/Lkl3cf9x+5AL7ZEapyq938tPw7gG62P26W+3WC1l9fvbXuB9cAarVtRyw+hEWFNuKtD7nLXRbkAHAVq7n2ZuzA7AjfaX1LLX+u6ZjFrzYikQUcoFn4qhLJ2CJIIKLSKupGK7TJcJn9GEFXP9WVii1kWtZ19NzyDDGOjN6H5FQo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Countess-Kate_3259
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy